const fs = require("fs");
const { PDFParse } = require("pdf-parse");


/**
 * Check whether extracted PDF text contains
 * meaningful content.
 */
function hasUsableText(text) {
    if (!text || typeof text !== "string") {
        return false;
    }

    // Remove whitespace and the page markers
    // generated by pdf-parse.
    const cleanedText = text
        .replace(/--\s*\d+\s+of\s+\d+\s*--/gi, "")
        .replace(/\s+/g, "")
        .trim();

    // If nothing meaningful remains,
    // the PDF is most likely scanned/image-based.
    return cleanedText.length > 20;
}


/**
 * Extract text from a text-based PDF.
 */
async function extractPdfText(filePath) {
    if (!fs.existsSync(filePath)) {
        throw new Error("PDF file not found.");
    }

    const pdfBuffer = fs.readFileSync(filePath);

    const parser = new PDFParse({
        data: pdfBuffer
    });

    const result = await parser.getText();

    await parser.destroy();

    // Check whether the PDF contains usable text.
    if (!hasUsableText(result.text)) {
        throw new Error(
            "PDF contains scanned images. Please upload the scanned invoice directly as a JPEG or PNG image."
        );
    }

    return {
        text: result.text,
        numberOfPages: result.total
    };
}


module.exports = {
    extractPdfText,
    hasUsableText
};